// Red Forge IDE Type Definitions

// US/NATO Classification Levels
export type SecurityLevel = 'UNCLASSIFIED' | 'CONFIDENTIAL' | 'SECRET' | 'TOP_SECRET';

// Swedish Classification Levels (FMV/SAK-IMS)
export type SwedishSecurityLevel = 'EJ_SEKRETESS' | 'BEGRANSAT_HEMLIG' | 'KONFIDENTIELL' | 'HEMLIG' | 'KVALIFICERAT_HEMLIG';

// Combined type for both systems
export type AnySecurityLevel = SecurityLevel | SwedishSecurityLevel;

// Classification system locale
export type ClassificationLocale = 'US' | 'SE';

export interface DualClassification {
  what: SecurityLevel;  // Capability/interface classification
  how: SecurityLevel;   // Implementation classification
}

export interface ClassifiedFile {
  id: string;
  name: string;
  content: string;
  language: 'typescript' | 'python' | 'rust' | 'markdown';
  dualClassification?: DualClassification;
  classification?: SecurityLevel; // For legacy single classification
  lastModified: Date;
  showPlaceholder?: boolean; // Show in tree even if user lacks clearance
  showFilename?: boolean;    // Reveal actual filename (vs [REDACTED])
}

export interface NetworkZone {
  type: 'white' | 'yellow' | 'red';
  allowedAI: 'external' | 'onprem' | 'none';
  internetAccess: boolean;
}

export interface ClassificationWarning {
  type: 'keyword_detection' | 'paste_protection' | 'untagged_content';
  severity: 'high' | 'medium' | 'low';
  message: string;
  location?: {
    line: number;
    column: number;
  };
}

// ============================================================================
// AI Service & Context Management Types
// ============================================================================

/**
 * AI service types with classification boundaries
 */
export type AIService = 'openai' | 'redforge-saas' | 'redforge-onsite' | 'none';

/**
 * AI service configuration
 */
export interface AIServiceConfig {
  service: AIService;
  displayName: string;
  maxClassification: SecurityLevel;
  openRouterModel: string;
  description: string;
  networkZone: 'white' | 'yellow' | 'red';
}

/**
 * Context block with classification tracking
 * Blocks can be selectively removed when downgrading AI service
 */
export interface ContextBlock {
  id: string;
  content: string;
  classificationLevel: SecurityLevel;
  source: 'user_message' | 'ai_response' | 'file_read' | 'code_selection';
  timestamp: Date;
  fileReference?: string; // If sourced from a file
  hidden?: boolean; // If hidden due to AI service downgrade
}

/**
 * Chat message with classification tracking
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  classificationLevel: SecurityLevel;
  aiService: AIService;
  timestamp: Date;
  contextBlocks?: string[]; // IDs of context blocks used
}

// ============================================================================
// Compliance & Audit Types
// ============================================================================

/**
 * Operation types for compliance checking and audit logging
 */
export type OperationType = 'read' | 'write' | 'delete' | 'export' | 'import' | 'query' | 'chat';

/**
 * User context for compliance validation
 */
export interface UserContext {
  id: string;
  clearance: SecurityLevel;
  networkZone: 'white' | 'yellow' | 'red';
  name?: string;
}

/**
 * Operation request to be validated by ComplianceEngine
 */
export interface Operation {
  type: OperationType;
  resource?: string;
  content?: string;
  user: UserContext;
  targetAI?: AIService; // For chat operations
  contextBlocks?: ContextBlock[]; // For chat operations
}

/**
 * Compliance decision result
 */
export interface Decision {
  allowed: boolean;
  reason?: string;
  warnings?: ClassificationWarning[];
  filteredContent?: string; // Content after classification filtering
}

/**
 * Audit trail entry (persisted in IndexedDB)
 */
export interface AuditEntry {
  id?: string; // Auto-generated by IndexedDB
  timestamp: Date;
  operation: OperationType;
  resource?: string;
  decision: 'allowed' | 'blocked';
  reason?: string;
  warnings?: ClassificationWarning[];
  user: UserContext;
  contentHash?: string; // Optional: SHA-256 hash of content for integrity
  aiService?: AIService; // For chat operations
  classificationLevel?: SecurityLevel; // Highest classification accessed
}

/**
 * Security scenario for demo purposes
 */
export interface SecurityScenario {
  id: string;
  name: string;
  description: string;
  userContext: UserContext;
  expectedBehavior: string;
}

